import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Transparent"
dynamic_padding = true
padding = { x = 20, y = 20 }
opacity = 1
blur = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 13

[colors]
# transparent_background_color = true

[colors.primary]
# background="#000000"

[keyboard]
bindings = [
  { key = "F", mods = "Super | Shift", action = "ToggleFullScreen" },
  { key = "M", mods = "Super | Shift", action = "ToggleMaximized" },
]
